import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Car, Zap, Plane, Coffee, RefreshCcw } from 'lucide-react';

const Calculator = () => {
  const [vehicle, setVehicle] = useState(50);
  const [electricity, setElectricity] = useState(200);
  const [flights, setFlights] = useState(1);
  const [diet, setDiet] = useState('average'); // vegan, vegetarian, average, meat-heavy

  // Very simplified calculation for demonstration
  const calculateFootprint = () => {
    let score = 0;
    score += vehicle * 0.2; // roughly 0.2 kg CO2 per km
    score += electricity * 0.5; // roughly 0.5 kg CO2 per kWh
    score += flights * 1000; // roughly 1000 kg per flight
    
    if (diet === 'vegan') score += 150;
    else if (diet === 'vegetarian') score += 200;
    else if (diet === 'average') score += 300;
    else if (diet === 'meat-heavy') score += 450;

    return Math.round(score);
  };

  const footprint = calculateFootprint();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-12 max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-4">Carbon Footprint Calculator</h1>
        <p className="text-slate-400 mb-4">
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. 
          The global average carbon footprint is around 4,000 kg per year, but to have the best chance of avoiding a 2℃ rise in global temperatures, the average needs to drop under 2,000 kg by 2050.
        </p>
        <p className="text-emerald-400 font-medium">
          Use this tool to estimate your monthly environmental impact and find out where you can make changes to reduce it.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Input Section */}
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="glass-card p-8 space-y-8"
        >
          {/* Vehicle */}
          <div>
            <label className="flex justify-between text-slate-200 mb-2">
              <span className="flex items-center space-x-2"><Car className="h-5 w-5 text-emerald-400" /> <span>Driving (km/week)</span></span>
              <span className="font-bold text-emerald-400">{vehicle} km</span>
            </label>
            <input 
              type="range" min="0" max="1000" value={vehicle} 
              onChange={(e) => setVehicle(Number(e.target.value))}
              className="w-full accent-emerald-500" 
            />
          </div>

          {/* Electricity */}
          <div>
            <label className="flex justify-between text-slate-200 mb-2">
              <span className="flex items-center space-x-2"><Zap className="h-5 w-5 text-emerald-400" /> <span>Electricity (kWh/month)</span></span>
              <span className="font-bold text-emerald-400">{electricity} kWh</span>
            </label>
            <input 
              type="range" min="0" max="1000" value={electricity} 
              onChange={(e) => setElectricity(Number(e.target.value))}
              className="w-full accent-emerald-500" 
            />
          </div>

          {/* Flights */}
          <div>
            <label className="flex justify-between text-slate-200 mb-2">
              <span className="flex items-center space-x-2"><Plane className="h-5 w-5 text-emerald-400" /> <span>Flights (per year)</span></span>
              <span className="font-bold text-emerald-400">{flights} flights</span>
            </label>
            <input 
              type="range" min="0" max="10" value={flights} 
              onChange={(e) => setFlights(Number(e.target.value))}
              className="w-full accent-emerald-500" 
            />
          </div>

          {/* Diet */}
          <div>
            <label className="flex items-center space-x-2 text-slate-200 mb-3">
              <Coffee className="h-5 w-5 text-emerald-400" /> <span>Diet Type</span>
            </label>
            <select 
              value={diet} 
              onChange={(e) => setDiet(e.target.value)}
              className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-slate-200 focus:outline-none focus:border-emerald-500"
            >
              <option value="vegan">Vegan</option>
              <option value="vegetarian">Vegetarian</option>
              <option value="average">Average</option>
              <option value="meat-heavy">Meat Heavy</option>
            </select>
          </div>

        </motion.div>

        {/* Result Section */}
        <motion.div 
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="glass-card p-8 flex flex-col justify-center items-center text-center relative overflow-hidden"
        >
          <div className="absolute top-[-50px] right-[-50px] w-40 h-40 bg-emerald-500/20 blur-3xl rounded-full" />
          
          <h2 className="text-xl text-slate-300 mb-2">Estimated Footprint</h2>
          <div className="text-6xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-teal-200 my-4">
            {footprint}
          </div>
          <p className="text-slate-400 mb-8">kg CO₂ per month</p>

          <div className="w-full bg-white/5 rounded-full h-4 mb-4 overflow-hidden border border-white/10">
            <div 
              className={`h-full ${footprint > 1500 ? 'bg-red-500' : footprint > 800 ? 'bg-yellow-500' : 'bg-emerald-500'} transition-all duration-500`} 
              style={{ width: `${Math.min((footprint / 2500) * 100, 100)}%` }}
            />
          </div>
          
          <p className="text-sm text-slate-300">
            {footprint < 800 ? "Great job! Your footprint is lower than average." : 
             footprint < 1500 ? "You have an average footprint. There is room for improvement!" : 
             "Your footprint is quite high. Consider reducing flights or meat consumption."}
          </p>

          <button 
            onClick={() => {setVehicle(50); setElectricity(200); setFlights(1); setDiet('average');}}
            className="mt-8 flex items-center space-x-2 text-slate-400 hover:text-white transition-colors"
          >
            <RefreshCcw className="h-4 w-4" /> <span>Reset Calculator</span>
          </button>
        </motion.div>

      </div>
    </div>
  );
};

export default Calculator;
